version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      GIT_SSH_COMMAND: ssh -vvv
    steps:
      - checkout
      - run: git clone git://git.yoctoproject.org/opkg
