version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    parallelism: 30
    steps:
      - checkout
      - run: wget get.sdkman.io
      - run: curl -s https://get.sdkman.io | bash
